USE [NewbieMVCDB]
GO

CREATE TABLE [dbo].[SYSTEMROLE](
	[ROLE_ID] [int] IDENTITY(1,1) NOT NULL,
	[ROLE_NAME] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_SYSTEMROLE] PRIMARY KEY CLUSTERED 
(
	[ROLE_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[ACCOUNT](
	[USER_ID] [int] IDENTITY(1,1) NOT NULL,
	[USER_ACCOUNT] [varchar](50) NOT NULL,
	[USER_NAME] [nvarchar](50) NOT NULL,
	[USER_PASSWORD] [varchar](50) NOT NULL,
	[CREATE_DATE] [datetime] NULL DEFAULT (getdate()),
	[LAST_LOGIN_DATE] [datetime] NULL,
	[ROLE_ID] [int] NOT NULL,
	[USER_ENABLE] [bit] NULL DEFAULT ((0)),
 CONSTRAINT [PK_ACCOUNT] PRIMARY KEY CLUSTERED 
(
	[USER_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[EMPLOYEE](
	[EMPLOYEE_ID] [int] IDENTITY(1,1) NOT NULL,
	[EMPLOYEE_Name] [nvarchar](20) NOT NULL,
	[EMPLOYEE_Title] [nvarchar](30) NULL,
	[EMPLOYEE_BirthDate] [datetime] NULL,
	[EMPLOYEE_HireDate] [datetime] NULL,
	[EMPLOYEE_Address] [nvarchar](60) NULL,
	[EMPLOYEE_HomePhone] [nvarchar](24) NULL,
	[EMPLOYEE_Extension] [nvarchar](4) NULL,
	[EMPLOYEE_PhotoPath] [nvarchar](255) NULL,
	[EMPLOYEE_Notes] [nvarchar](max) NULL,
	[EMPLOYEE_ManagerID] [int] NULL,
	[EMPLOYEE_Salary] [int] NULL,
 CONSTRAINT [PK_EMPLOYEE] PRIMARY KEY CLUSTERED 
(
	[EMPLOYEE_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[LOG_LOGIN](
	[LOG_ID] [int] IDENTITY(1,1) NOT NULL,
	[ACCOUNT_ID] [int] NOT NULL,
	[LOGIN_DATE] [datetime] NOT NULL
) ON [PRIMARY]
GO


INSERT INTO [dbo].[SYSTEMROLE] ([ROLE_NAME]) 
VALUES (N'管理者'), (N'一般使用者')

INSERT [dbo].[ACCOUNT] ([USER_ACCOUNT], [USER_NAME], [USER_PASSWORD], [CREATE_DATE], [LAST_LOGIN_DATE], [ROLE_ID], [USER_ENABLE]) 
VALUES (N'Mary', N'Mary', N'1234', getdate(), NULL, 1, 1)
	, (N'George', N'George', N'1234', getdate(), NULL, 2, 1)
	, (N'Peter', N'Peter', N'1234', getdate(), NULL, 2, 0)

